In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from keras.layers import Dense
from keras.models import Sequential
from keras.preprocessing.text import Tokenizer

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
data=pd.read_csv("train_utf.csv")

In [3]:
data.head()

ItemID Sentiment                                      SentimentText
0       1  Negative                       is so sad for my APL frie...
1       2  Negative                     I missed the New Moon trail...
2       3  Positive                            omg its already 7:30 :O
3       4  Negative            .. Omgaga. Im sooo  im gunna CRy. I'...
4       5  Negative           i think mi bf is cheating on me!!!   ...

In [4]:
data.SentimentText[3]

"          .. Omgaga. Im sooo  im gunna CRy. I've been at this dentist since 11.. I was suposed 2 just get a crown put on (30mins)..."

In [5]:
data.Sentiment.value_counts()

Positive    56457
Negative    43532
Name: Sentiment, dtype: int64

In [6]:
train_size=int(len(data)*.8)

In [7]:
train_text=data['SentimentText'][:train_size]
train_sent=data['Sentiment'][:train_size]

In [8]:
train_sent

0        Negative
1        Negative
2        Positive
3        Negative
4        Negative
5        Negative
6        Positive
7        Negative
8        Positive
9        Positive
10       Negative
11       Positive
12       Negative
13       Negative
14       Negative
15       Negative
16       Negative
17       Positive
18       Negative
19       Negative
20       Negative
21       Negative
22       Positive
23       Negative
24       Negative
25       Negative
26       Negative
27       Negative
28       Positive
29       Negative
           ...   
79961    Negative
79962    Positive
79963    Positive
79964    Negative
79965    Positive
79966    Positive
79967    Positive
79968    Negative
79969    Positive
79970    Positive
79971    Negative
79972    Negative
79973    Negative
79974    Negative
79975    Positive
79976    Positive
79977    Positive
79978    Positive
79979    Negative
79980    Positive
79981    Positive
79982    Positive
79983    Negative
79984    Negative
79985    N

In [9]:
test_text=data['SentimentText'][train_size:]
test_sent=data['Sentiment'][train_size:]

In [66]:
max_words=1500
tokenize=Tokenizer(num_words=max_words,char_level=False)

In [67]:
tokenize.fit_on_texts(train_text)
x_train=tokenize.texts_to_matrix(train_text)
x_tests=tokenize.texts_to_matrix(test_text)

In [12]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
tokenize.index_word

{1: 'i',
 2: 'the',
 3: 'to',
 4: 'you',
 5: 'a',
 6: 'it',
 7: 'and',
 8: 'my',
 9: 'for',
 10: 'is',
 11: 'in',
 12: 'me',
 13: 'that',
 14: 'of',
 15: 'quot',
 16: 'have',
 17: 'on',
 18: 'so',
 19: 'but',
 20: "i'm",
 21: 'be',
 22: 'was',
 23: 'not',
 24: 'just',
 25: 'your',
 26: 'are',
 27: 'good',
 28: 'with',
 29: 'like',
 30: 'no',
 31: 'at',
 32: 'get',
 33: 'lol',
 34: 'u',
 35: 'too',
 36: 'all',
 37: 'this',
 38: 'now',
 39: 'up',
 40: 'do',
 41: 'love',
 42: 'know',
 43: "it's",
 44: 'out',
 45: 'we',
 46: 'thanks',
 47: 'what',
 48: 'will',
 49: 'one',
 50: 'go',
 51: "don't",
 52: 'can',
 53: 'day',
 54: 'if',
 55: 'about',
 56: 'amp',
 57: 'http',
 58: 'see',
 59: 'well',
 60: 'there',
 61: 'how',
 62: 'time',
 63: 'when',
 64: 'got',
 65: 'im',
 66: 'oh',
 67: 'as',
 68: 'think',
 69: 'from',
 70: 'they',
 71: 'haha',
 72: 'am',
 73: 'really',
 74: 'going',
 75: 'work',
 76: 'hope',
 77: 'had',
 78: 'its',
 79: "can't",
 80: 'sorry',
 81: 'still',
 82: 'or',
 83: 'so

In [14]:
tokenize.word_docs

defaultdict(int,
            {'friend': 509,
             'my': 10410,
             'for': 9386,
             'apl': 1,
             'sad': 1271,
             'so': 6844,
             'is': 9267,
             'i': 30086,
             'missed': 547,
             'moon': 83,
             'the': 19841,
             'new': 1444,
             'trailer': 53,
             '7': 209,
             'already': 714,
             'o': 507,
             'its': 1903,
             'omg': 549,
             '30': 219,
             'crown': 10,
             'gunna': 42,
             'dentist': 29,
             '2': 1634,
             'this': 3794,
             'sooo': 213,
             '30mins': 5,
             "i've": 1091,
             'been': 1691,
             'im': 2230,
             '11': 103,
             'cry': 192,
             'on': 7300,
             'put': 448,
             'at': 4064,
             'omgaga': 1,
             'suposed': 1,
             'just': 5351,
             'since': 437,
  

In [15]:
encoder=LabelEncoder()
encoder.fit(train_sent)

LabelEncoder()

In [16]:
y_train=encoder.transform(train_sent)
y_test=encoder.transform(test_sent)

In [17]:
encoder.classes_

array(['Negative', 'Positive'], dtype=object)

In [18]:
y_train

array([0, 0, 1, ..., 1, 0, 1], dtype=int64)

In [19]:
import numpy as np

In [20]:
np.unique(y_train)

array([0, 1], dtype=int64)

In [21]:
from keras import Sequential

In [22]:
model=Sequential()

In [23]:
model.add(Dense(512,input_shape=(max_words,),activation='relu'))

In [24]:
model

In [25]:
model.add(Dense(2,activation='softmax'))

In [26]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=['accuracy'])

In [27]:
from keras import utils

In [28]:
y_train_new=utils.to_categorical(y_train)
y_test_new=utils.to_categorical(y_test)

In [35]:
history=model.fit(x_train,y_train_new,batch_size=32,epochs=2,verbose=1,validation_split=0.1)

Train on 71991 samples, validate on 8000 samples
Epoch 1/2
71991/71991 [==============================] - 60s 830us/step - loss: 0.4907 - acc: 0.7612 - val_loss: 0.4837 - val_acc: 0.7626
Epoch 2/2
71991/71991 [==============================] - 61s 854us/step - loss: 0.4169 - acc: 0.8089 - val_loss: 0.4916 - val_acc: 0.7664


In [36]:
score=model.evaluate(x_tests,y_test_new)

19998/19998 [==============================] - 3s 140us/step


In [37]:
score

[0.49349032472534077, 0.7620762075969179]

In [54]:
new=tokenize.texts_to_matrix(["""PK saying he lost becos 150cr given to voters is a real insult to voters bcos  he’s saying people who he wants to serve r corrupt.If voters wanted him they could take money from othrs nd still voted him.If PK also has to give money for votes what’s point in being PK? Just asking"""])

In [55]:
k=model.predict_classes(new)

In [56]:
encoder.classes_[k]

array(['Negative'], dtype=object)

In [41]:
model.save("project.h5")

In [68]:
import pickle
f=open('tok.pkl','wb')
pickle.dump(tokenize,f)

In [70]:
#!/usr/bin/env python
# coding: utf-8

# In[3]:


from tkinter import *
from keras.models import load_model
from keras.preprocessing.text import Tokenizer
with open('tok.pkl','rb') as file:
    tokenize=pickle.load(file)
model = load_model('project.h5')
top = Tk()
top.geometry("550x300+300+150")
top.resizable(width=True, height=True)

L1 = Label(top, text="Enter Text For Prediction")
L1.pack()
E1 = Entry(top, bd =5)
E1.pack()
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=['accuracy'])
#max_words=1500
#tokenize=Tokenizer(num_words=max_words,char_level=False)
def predict1():
    print("Prediction on progress..")
    entered_input=E1.get()
    print("Entered Input",entered_input)
    entered_input=tokenize.texts_to_matrix([entered_input])
    print(entered_input)
    y_pred=model.predict_classes(entered_input)
    print(y_pred)
    if y_pred[0]==0:
        text="The input is a NEGATIVE sentiment"
        
    else:
        text="The input is a POSITIVE sentiment"

    L2 = Label(top, text="Prediction: "+text)
    L2.pack()


B = Button(top, text ="Predict", command = predict1)
B.pack(pady=10)

top.mainloop()


# In[ ]:





# In[ ]:




